apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color2
  labels:
    name: simple-webapp-color2
spec:
  containers:
  - name: simple-webapp-color2
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: app-config
